server:
  port: 9020
  servlet:
    context-path: /ppi/v2
spring:
  application:
    name: booking-service
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookingBD;
    platform: h2
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

